// Shared contract types, sections, and legal text
// Used by both HR.jsx (carrier side) and SignContract.jsx (public signing page)

export const CONTRACT_TYPES = [
  { id:'lease', label:'Owner-Operator Lease Agreement', desc:'49 CFR §376.12 compliant equipment lease' },
  { id:'ic', label:'Independent Contractor Agreement', desc:'1099 contractor relationship terms' },
  { id:'non_compete', label:'Non-Compete / Non-Solicitation', desc:'Broker and customer protection clause' },
  { id:'custom', label:'Custom Contract', desc:'Upload your own contract document' },
]

export const LEASE_SECTIONS = [
  'Equipment Description (VIN, Year, Make, Model)',
  'Lease Duration & Renewal Terms',
  'Compensation Structure (% of revenue, per-mile, or flat)',
  'Fuel, Insurance & Toll Responsibility',
  'Escrow & Deduction Policies',
  'Maintenance & Repair Obligations',
  'Insurance Requirements & Minimums',
  'Cargo Liability',
  '45-Day Settlement Guarantee (FMCSA)',
  'Termination & Return of Equipment',
]

export const IC_SECTIONS = [
  'Independent Contractor Status (not W-2)',
  'Compensation & Pay Schedule',
  'Tax Obligations (1099)',
  'Insurance Requirements',
  'Equipment & Operating Authority',
  'Load Acceptance / Right to Refuse',
  'Non-Compete / Non-Solicitation',
  'Confidentiality',
  'Termination Terms (30-day notice)',
  'Dispute Resolution & Governing Law',
]

export const LEASE_LEGAL_TEXT = {
  'Equipment Description (VIN, Year, Make, Model)': 'The Carrier hereby leases to the Owner-Operator the following described equipment for use in the transportation of property under the Carrier\'s operating authority. The Owner-Operator represents that they are the legal owner of the vehicle described herein and that it is free from all liens and encumbrances unless otherwise noted. Equipment details including VIN, year, make, model, and license plate shall be recorded in Exhibit A attached hereto.',
  'Lease Duration & Renewal Terms': 'This lease agreement shall commence on the Start Date specified above and shall continue for the duration indicated, or if open-ended, shall remain in effect until terminated by either party upon thirty (30) days written notice. The lease may be renewed by mutual written agreement of both parties. Any renewal shall be subject to the same terms and conditions unless otherwise agreed upon in writing.',
  'Compensation Structure (% of revenue, per-mile, or flat)': 'The Carrier shall compensate the Owner-Operator according to the pay structure specified in this agreement. Compensation shall be calculated based on the gross revenue generated by the Owner-Operator\'s equipment. Detailed settlement statements shall be provided to the Owner-Operator within fifteen (15) business days of delivery of each load, showing all compensation earned and any authorized deductions.',
  'Fuel, Insurance & Toll Responsibility': 'The Owner-Operator shall be responsible for all fuel costs, tolls, and scales associated with the operation of the leased equipment unless otherwise specified. The Carrier shall maintain primary liability insurance as required by federal regulations. The Owner-Operator shall maintain occupational accident insurance and non-trucking liability coverage at their own expense. Any fuel surcharges or fuel discounts shall be passed through to the Owner-Operator as specified in the settlement.',
  'Escrow & Deduction Policies': 'The Carrier may require an escrow deposit from the Owner-Operator, not to exceed the amount permitted by FMCSA regulations. All deductions from the Owner-Operator\'s compensation must be itemized on each settlement statement. No deductions shall be made without the prior written authorization of the Owner-Operator. Upon termination, all escrow funds shall be returned within forty-five (45) days, less any amounts owed by the Owner-Operator to the Carrier.',
  'Maintenance & Repair Obligations': 'The Owner-Operator shall be solely responsible for maintaining the leased equipment in safe operating condition in compliance with all Federal Motor Carrier Safety Regulations (FMCSRs). The Owner-Operator shall perform or cause to be performed all necessary maintenance, repairs, and inspections. The Carrier shall have no obligation to maintain or repair the equipment. Any Carrier-provided maintenance shall be at the Carrier\'s standard rates and deducted from settlement with prior authorization.',
  'Insurance Requirements & Minimums': 'The Carrier shall procure and maintain primary liability insurance coverage for the Owner-Operator\'s vehicle while operating under the Carrier\'s authority, meeting or exceeding the minimum requirements of 49 CFR §387. The Owner-Operator shall maintain: (a) Non-Trucking Liability insurance with minimum limits of $1,000,000; (b) Physical Damage/Cargo insurance as required; (c) Occupational Accident insurance. Proof of insurance must be provided prior to commencement of operations and maintained throughout the lease term.',
  'Cargo Liability': 'The Owner-Operator shall exercise due care in the handling, loading, and transportation of all cargo. The Owner-Operator shall be liable for cargo loss or damage caused by the Owner-Operator\'s negligence. The Carrier maintains cargo insurance as required by law. Any cargo claims attributed to the Owner-Operator\'s negligence may be deducted from the Owner-Operator\'s compensation after investigation and with written notice, subject to the deduction policies outlined herein.',
  '45-Day Settlement Guarantee (FMCSA)': 'In accordance with 49 CFR §376.12(h), upon termination of this lease, the Carrier shall provide a final settlement to the Owner-Operator within forty-five (45) days. The final settlement shall include all compensation owed, return of all escrow funds less documented amounts owed, and an itemized statement of all deductions. Failure to comply with this requirement constitutes a violation of federal regulations.',
  'Termination & Return of Equipment': 'Either party may terminate this lease agreement upon thirty (30) days written notice. The Carrier may terminate immediately for cause, including but not limited to: violation of federal safety regulations, loss of CDL, positive drug or alcohol test, or material breach of this agreement. Upon termination, the Owner-Operator shall return any Carrier-provided equipment (placards, ELD devices, transponders) within five (5) business days. The Owner-Operator\'s own equipment shall be released promptly upon completion of final settlement.',
}

export const IC_LEGAL_TEXT = {
  'Independent Contractor Status (not W-2)': 'The parties agree that the Owner-Operator is an independent contractor and not an employee, agent, or servant of the Carrier. The Owner-Operator shall have the right to control the manner and means of performing transportation services, including the right to select routes, rest stops, and work schedules. The Carrier exercises no control over the Owner-Operator except as necessary to ensure compliance with federal and state regulations. Nothing in this agreement shall be construed to create an employer-employee relationship.',
  'Compensation & Pay Schedule': 'The Carrier shall compensate the Owner-Operator according to the pay structure specified in this agreement. Settlement statements shall be issued on a weekly basis, with payment made within seven (7) business days of the settlement period close. Each settlement shall itemize gross revenue, fuel surcharges, accessorial charges, and all authorized deductions. The Owner-Operator shall have the right to examine the freight bills and related documentation for all loads transported.',
  'Tax Obligations (1099)': 'As an independent contractor, the Owner-Operator is solely responsible for the payment of all federal, state, and local taxes, including but not limited to income tax, self-employment tax, and estimated quarterly tax payments. The Carrier shall issue an IRS Form 1099-NEC to the Owner-Operator for all compensation paid during each calendar year. The Owner-Operator shall provide a completed W-9 form prior to the commencement of services.',
  'Insurance Requirements': 'The Owner-Operator shall maintain, at their own expense: (a) Commercial Auto Liability insurance with minimum limits of $1,000,000 per occurrence; (b) Cargo insurance with minimum limits of $100,000; (c) Workers\' Compensation or Occupational Accident insurance as required by applicable law; (d) General Liability insurance with minimum limits of $1,000,000. All insurance policies shall name the Carrier as an additional insured. Certificates of insurance must be provided prior to commencement of services and upon each renewal.',
  'Equipment & Operating Authority': 'The Owner-Operator shall provide all equipment necessary for the performance of services, including but not limited to the motor vehicle(s) described herein, all required safety equipment, and any specialized equipment required for specific loads. The Owner-Operator may operate under the Carrier\'s operating authority (MC number) for loads dispatched by the Carrier, or may operate under their own authority for other loads. The Owner-Operator shall maintain their equipment in compliance with all FMCSA regulations.',
  'Load Acceptance / Right to Refuse': 'The Owner-Operator shall have the unrestricted right to accept or reject any load offered by the Carrier without penalty or adverse consequence. The Carrier shall not require the Owner-Operator to accept any minimum number of loads. Once a load is accepted, the Owner-Operator shall be responsible for the timely pickup and delivery in accordance with the load confirmation. The Owner-Operator may also perform services for other carriers or shippers, provided such services do not interfere with accepted commitments to the Carrier.',
  'Non-Compete / Non-Solicitation': 'During the term of this agreement and for a period of twelve (12) months following termination, the Owner-Operator agrees not to directly solicit or contact the Carrier\'s customers, brokers, or shippers for the purpose of providing competing transportation services, where such relationships were established through the Carrier. This provision shall not restrict the Owner-Operator from accepting loads from load boards or other public sources, even if such loads originate from the Carrier\'s customers.',
  'Confidentiality': 'The Owner-Operator agrees to maintain the confidentiality of all proprietary information, including but not limited to customer lists, rate agreements, business strategies, and financial information of the Carrier. This obligation shall survive the termination of this agreement for a period of two (2) years. The Owner-Operator shall not disclose confidential information to any third party without the prior written consent of the Carrier.',
  'Termination Terms (30-day notice)': 'Either party may terminate this agreement upon thirty (30) days written notice to the other party. The Carrier may terminate immediately for cause, including: material breach of this agreement, suspension or revocation of CDL, positive drug or alcohol test result, or violation of federal safety regulations. Upon termination, the Owner-Operator shall complete all accepted loads in transit and return all Carrier-provided property. Final settlement shall be issued within forty-five (45) days of termination.',
  'Dispute Resolution & Governing Law': 'Any dispute arising under this agreement shall first be submitted to mediation before a mutually agreed-upon mediator. If mediation fails to resolve the dispute within thirty (30) days, either party may pursue binding arbitration under the rules of the American Arbitration Association. This agreement shall be governed by and construed in accordance with federal transportation law and the laws of the state in which the Carrier\'s principal office is located. Each party shall bear their own costs and attorney fees unless otherwise ordered.',
}

// Helper to get sections by contract type
export function getSectionsForType(type) {
  if (type === 'lease') return LEASE_SECTIONS
  if (type === 'ic') return IC_SECTIONS
  return []
}

export function getLegalTextForType(type) {
  if (type === 'lease') return LEASE_LEGAL_TEXT
  if (type === 'ic') return IC_LEGAL_TEXT
  return {}
}

// Build pay description string
export function payDescription(payStructure, payRate) {
  if (payStructure === 'percent') return `${payRate}% of gross revenue`
  if (payStructure === 'permile') return `$${payRate} per mile`
  return `$${payRate} per load`
}
