import React, { useState } from 'react'
import { Ic } from '../shared'
import { useApp } from '../../../context/AppContext'
import { apiFetch } from '../../../lib/api'
import { Shield, Download } from 'lucide-react'

// ── DOT Audit Package Export ──────────────────────────────────────────────────
function DOTAuditExport() {
  const { showToast } = useApp()
  const [loading, setLoading] = useState(false)
  const [months, setMonths] = useState(12)

  const handleExport = async () => {
    setLoading(true)
    try {
      const res = await apiFetch(`/api/dot-audit-package?months=${months}`)
      if (!res.ok) throw new Error('Failed to generate package')
      const pkg = await res.json()

      // Generate PDF
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ unit: 'pt', format: 'letter' })
      const W = 612, P = 40
      const navy = [26, 54, 93], blk = [17, 24, 39], gry = [107, 114, 128], bdr = [229, 231, 235], red = [220, 38, 38], grn = [34, 176, 104]

      let y = 30

      const addPage = () => { doc.addPage(); y = 30 }
      const checkPage = (need = 40) => { if (y > 740 - need) addPage() }

      // Cover page
      doc.setFillColor(...navy); doc.rect(0, 0, W, 4, 'F')
      doc.setFont('helvetica', 'bold'); doc.setFontSize(24); doc.setTextColor(...navy)
      doc.text('DOT / FMCSA AUDIT PACKAGE', P, y += 30)
      doc.setFontSize(10); doc.setTextColor(...gry)
      doc.text(`Generated: ${new Date().toLocaleDateString()} · Period: ${pkg.period}`, P, y += 18)
      doc.text('Generated by Qivori AI TMS · qivori.com', P, y += 14)
      doc.setDrawColor(...bdr); doc.line(P, y += 10, W - P, y)

      // Company info
      y += 20; doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...navy)
      doc.text('CARRIER INFORMATION', P, y)
      y += 16; doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...blk)
      ;[['Company', pkg.company.name], ['MC#', pkg.company.mc_number], ['DOT#', pkg.company.dot_number], ['Address', pkg.company.address], ['Phone', pkg.company.phone]].forEach(([l, v]) => {
        doc.text(`${l}: ${v}`, P, y); y += 14
      })

      // Compliance summary
      y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y); y += 16
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...navy)
      doc.text('COMPLIANCE SUMMARY', P, y)
      y += 16; doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
      doc.setTextColor(...(pkg.compliance.audit_ready ? grn : red))
      doc.text(pkg.compliance.audit_ready ? 'AUDIT READY — All clear' : `NOT AUDIT READY — ${pkg.compliance.critical_issues} critical issue(s)`, P, y)
      y += 14; doc.setTextColor(...blk)
      doc.text(`Score: ${pkg.compliance.score}/100 (${pkg.compliance.grade}) · Critical: ${pkg.compliance.critical_issues} · Warnings: ${pkg.compliance.warnings.length}`, P, y)

      // Issues
      if (pkg.compliance.issues.length > 0) {
        y += 20; doc.setFont('helvetica', 'bold'); doc.setTextColor(...red); doc.text('CRITICAL ISSUES:', P, y)
        pkg.compliance.issues.forEach(issue => {
          y += 14; checkPage(); doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...red)
          doc.text(`• ${issue.item} (${issue.reg})`, P + 10, y)
        })
      }

      // Drivers
      addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
      doc.text(`DRIVER QUALIFICATION FILES (${pkg.drivers.length} drivers)`, P, y += 20)
      y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

      pkg.drivers.forEach(d => {
        checkPage(60); y += 16
        doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(...blk)
        doc.text(d.name, P, y)
        y += 14; doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...gry)
        doc.text(`CDL: ${d.cdl_number} · Expires: ${d.cdl_expiry} (${d.cdl_status}) · Medical: ${d.medical_card_expiry} (${d.medical_status}) · Hired: ${d.hire_date}`, P, y)
        if (d.cdl_status === 'EXPIRED' || d.medical_status === 'EXPIRED') {
          y += 12; doc.setTextColor(...red); doc.setFont('helvetica', 'bold')
          doc.text('⚠ EXPIRED — DO NOT DISPATCH', P + 10, y)
        }
      })

      // Vehicles
      addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
      doc.text(`VEHICLE RECORDS (${pkg.vehicles.length} vehicles)`, P, y += 20)
      y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

      pkg.vehicles.forEach(v => {
        checkPage(50); y += 16
        doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(...blk)
        doc.text(`Unit ${v.unit} — ${v.year} ${v.make} ${v.model}`, P, y)
        y += 14; doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...gry)
        doc.text(`VIN: ${v.vin} · Plate: ${v.plate} ${v.plate_state} · Reg: ${v.registration_expiry} · Ins: ${v.insurance_expiry} · Odo: ${v.odometer}`, P, y)
      })

      // DVIRs
      addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
      doc.text(`DVIR INSPECTION HISTORY (${pkg.dvirs.total} records)`, P, y += 20)
      y += 6; doc.setFontSize(10); doc.setTextColor(...gry)
      doc.text(`Last 30 days: ${pkg.dvirs.last_30_days} | Passed: ${pkg.dvirs.passed} | Defects found: ${pkg.dvirs.defects_found}`, P, y += 14)
      y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

      pkg.dvirs.records.slice(0, 30).forEach(d => {
        checkPage(20); y += 14
        doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
        doc.setTextColor(...(d.status === 'safe' ? grn : red))
        doc.text(`${d.date} · ${d.vehicle} · ${d.driver} · ${d.status.toUpperCase()}${d.defects.length ? ' — ' + d.defects.join(', ') : ''}`, P, y)
      })

      // Load history summary
      addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
      doc.text(`LOAD HISTORY (${pkg.loads.total} loads)`, P, y += 20)
      y += 6; doc.setFontSize(10); doc.setTextColor(...gry)
      doc.text(`Delivered: ${pkg.loads.delivered} | Cancelled: ${pkg.loads.cancelled}`, P, y += 14)
      y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

      pkg.loads.records.slice(0, 25).forEach(l => {
        checkPage(16); y += 14
        doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...blk)
        doc.text(`${l.load || '—'} · ${l.origin || '—'} → ${l.destination || '—'} · ${l.driver || '—'} · ${l.status} · $${l.rate || 0} · ${l.miles || 0}mi`, P, y)
      })

      // Fuel receipts (IFTA audit requirement)
      if (pkg.expenses.fuel_receipts?.length > 0) {
        addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
        doc.text(`FUEL PURCHASE RECORDS — IFTA (${pkg.expenses.fuel_receipts.length} receipts)`, P, y += 20)
        y += 6; doc.setFontSize(10); doc.setTextColor(...gry)
        doc.text(`Total fuel: $${pkg.expenses.fuel_total?.toLocaleString()} | Total gallons: ${pkg.expenses.fuel_gallons?.toLocaleString()} | Avg $/gal: $${pkg.expenses.fuel_gallons > 0 ? (pkg.expenses.fuel_total / pkg.expenses.fuel_gallons).toFixed(3) : '—'}`, P, y += 14)
        y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

        // Table header
        y += 14; doc.setFillColor(248, 250, 252); doc.rect(P, y - 4, W - P * 2, 16, 'F')
        doc.setFont('helvetica', 'bold'); doc.setFontSize(7); doc.setTextColor(...gry)
        doc.text('DATE', P + 4, y + 6); doc.text('STATE', P + 65, y + 6); doc.text('STATION', P + 100, y + 6)
        doc.text('GALLONS', P + 250, y + 6); doc.text('$/GAL', P + 310, y + 6); doc.text('AMOUNT', P + 370, y + 6)
        y += 18

        pkg.expenses.fuel_receipts.forEach(r => {
          checkPage(14); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...blk)
          doc.text(r.date || '—', P + 4, y); doc.text(r.state, P + 65, y)
          doc.text((r.merchant || '—').slice(0, 25), P + 100, y)
          doc.text(String(r.gallons || '—'), P + 250, y)
          doc.text(r.price_per_gallon ? '$' + r.price_per_gallon.toFixed(3) : '—', P + 310, y)
          doc.setTextColor(...red); doc.text('$' + r.amount.toLocaleString(), P + 370, y)
          doc.setTextColor(...blk)
          doc.setDrawColor(240, 240, 240); doc.line(P, y + 4, W - P, y + 4)
          y += 14
        })
      }

      // Maintenance records
      if (pkg.expenses.maintenance_receipts?.length > 0) {
        addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
        doc.text(`MAINTENANCE & REPAIR RECORDS (${pkg.expenses.maintenance_receipts.length} records)`, P, y += 20)
        y += 6; doc.setFontSize(10); doc.setTextColor(...gry)
        doc.text(`Total maintenance cost: $${pkg.expenses.maintenance?.toLocaleString()}`, P, y += 14)
        y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

        pkg.expenses.maintenance_receipts.forEach(r => {
          checkPage(14); y += 14
          doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...blk)
          doc.text(`${r.date || '—'} · ${r.merchant || '—'} · $${r.amount.toLocaleString()} · ${r.notes || '—'}`, P, y)
        })
      }

      // DOT Compliance Checklist
      if (pkg.dot_checklist) {
        addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
        doc.text('DOT/FMCSA COMPLIANCE CHECKLIST', P, y += 20)
        y += 6; doc.setFontSize(9); doc.setTextColor(...gry)
        doc.text('Required records per FMCSA Parts 390-399', P, y += 14)
        y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

        const checklistItems = [
          ['Carrier Identification (MC/DOT)', pkg.dot_checklist.carrier_identification, 'FMCSA §390.19'],
          ['Operating Authority', pkg.dot_checklist.operating_authority, 'FMCSA §392.9a'],
          ['Insurance Certificate (min $750K)', pkg.dot_checklist.insurance_certificate, 'FMCSA §387'],
          ['Driver Qualification Files', pkg.dot_checklist.driver_qualification_files, 'FMCSA §391'],
          ['CDL Copies on File', pkg.dot_checklist.cdl_on_file, 'FMCSA §391.51'],
          ['Medical Cards Current', pkg.dot_checklist.medical_cards_current, 'FMCSA §391.43'],
          ['Vehicle Registration', pkg.dot_checklist.vehicle_registration, 'FMCSA §392.2'],
          ['Vehicle Inspection Records (DVIR)', pkg.dot_checklist.vehicle_inspection_records, 'FMCSA §396.11'],
          ['Hours of Service Logs', pkg.dot_checklist.hours_of_service_logs, 'FMCSA §395'],
          ['Fuel Tax Records (IFTA)', pkg.dot_checklist.fuel_tax_records, 'IFTA §R1320'],
          ['Maintenance Records', pkg.dot_checklist.maintenance_records, 'FMCSA §396.3'],
          ['Accident Register', pkg.dot_checklist.accident_register, 'FMCSA §390.15'],
          ['Drug & Alcohol Testing', pkg.dot_checklist.drug_alcohol_testing, 'FMCSA §382'],
        ]

        checklistItems.forEach(([label, passes, reg]) => {
          y += 18; checkPage(18)
          doc.setFont('helvetica', 'bold'); doc.setFontSize(10)
          doc.setTextColor(...(passes ? grn : red))
          doc.text(passes ? 'PASS' : 'FAIL', P + 4, y)
          doc.setFont('helvetica', 'normal'); doc.setTextColor(...blk)
          doc.text(label, P + 40, y)
          doc.setTextColor(...gry); doc.setFontSize(8)
          doc.text(reg, W - P - 10, y, { align: 'right' })
        })

        const passCount = checklistItems.filter(([, p]) => p).length
        y += 24; doc.setFont('helvetica', 'bold'); doc.setFontSize(11)
        doc.setTextColor(...(passCount === checklistItems.length ? grn : red))
        doc.text(`${passCount}/${checklistItems.length} items compliant${passCount === checklistItems.length ? ' — AUDIT READY' : ' — ACTION REQUIRED'}`, P, y)
      }

      // Documents on file
      if (pkg.documents?.length > 0) {
        addPage(); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(...navy)
        doc.text(`DOCUMENTS ON FILE (${pkg.documents.length})`, P, y += 20)
        y += 10; doc.setDrawColor(...bdr); doc.line(P, y, W - P, y)

        pkg.documents.slice(0, 30).forEach(d => {
          checkPage(14); y += 14
          doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...blk)
          doc.text(`${d.uploaded || '—'} · ${(d.type || '—').toUpperCase()} · ${d.name || '—'}`, P, y)
        })
      }

      // Footer on all pages
      const pages = doc.getNumberOfPages()
      for (let i = 1; i <= pages; i++) {
        doc.setPage(i)
        doc.setDrawColor(...bdr); doc.line(P, 760, W - P, 760)
        doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(...gry)
        doc.text(`DOT Audit Package · ${pkg.company.name} · MC ${pkg.company.mc_number} · Page ${i}/${pages} · Qivori AI TMS`, W / 2, 775, { align: 'center' })
      }

      doc.save(`DOT-Audit-Package-${pkg.company.mc_number || 'carrier'}-${new Date().toISOString().split('T')[0]}.pdf`)
      showToast('', 'Audit Package Downloaded', `${pages} pages · ${pkg.drivers.length} drivers · ${pkg.vehicles.length} vehicles · ${pkg.dvirs.total} DVIRs`)

    } catch (err) {
      showToast('', 'Export Failed', err.message || 'Try again')
    }
    setLoading(false)
  }

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px', background: 'var(--surface)', border: '1px solid rgba(240,165,0,0.2)', borderRadius: 10 }}>
      <Ic icon={Shield} size={18} color="var(--accent)" />
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--text)' }}>DOT Audit Package</div>
        <div style={{ fontSize: 10, color: 'var(--muted)' }}>One-click export: drivers, vehicles, DVIRs, insurance, load history</div>
      </div>
      <select value={months} onChange={e => setMonths(parseInt(e.target.value))}
        style={{ padding: '5px 10px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface2)', color: 'var(--text)', fontSize: 11 }}>
        <option value={6}>6 months</option>
        <option value={12}>12 months</option>
        <option value={24}>24 months</option>
        <option value={36}>3 years</option>
        <option value={60}>5 years</option>
      </select>
      <button onClick={handleExport} disabled={loading} className="btn btn-primary" style={{ fontSize: 11, padding: '8px 16px' }}>
        <Ic icon={Download} size={12} /> {loading ? 'Generating...' : 'Export PDF'}
      </button>
    </div>
  )
}

export default DOTAuditExport
